"""Add Fitur cart,wallet,search_history,wishlist, and discount

Revision ID: 090d67efeb65
Revises: e336874bac68
Create Date: 2024-10-02 22:41:27.777937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '090d67efeb65'
down_revision = 'e336874bac68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_history',
    sa.Column('id_search', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('search_term', sa.String(length=255), nullable=False),
    sa.Column('date_searched', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('id_search')
    )
    op.create_table('wallet',
    sa.Column('id_wallet', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['id_user'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('id_wallet')
    )
    op.create_table('cart',
    sa.Column('id_cart', sa.Integer(), nullable=False),
    sa.Column('id_shoe', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_shoe'], ['shoe_detail.shoe_detail_id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('id_cart')
    )
    op.create_table('discount',
    sa.Column('id_discount', sa.Integer(), nullable=False),
    sa.Column('id_shoe', sa.Integer(), nullable=False),
    sa.Column('discount_code', sa.String(length=50), nullable=False),
    sa.Column('discount_value', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('expiration_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['id_shoe'], ['shoe_detail.shoe_detail_id'], ),
    sa.PrimaryKeyConstraint('id_discount'),
    sa.UniqueConstraint('discount_code')
    )
    op.create_table('wishlist',
    sa.Column('id_wishlist', sa.Integer(), nullable=False),
    sa.Column('id_shoe', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_shoe'], ['shoe_detail.shoe_detail_id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('id_wishlist')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wishlist')
    op.drop_table('discount')
    op.drop_table('cart')
    op.drop_table('wallet')
    op.drop_table('search_history')
    # ### end Alembic commands ###
