"""Perbaiki Struktur Table

Revision ID: 0e3bcf30ff4e
Revises: 92f9a535e916
Create Date: 2024-10-03 16:37:35.934680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e3bcf30ff4e'
down_revision = '92f9a535e916'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_updated', sa.DateTime(), nullable=True))

    with op.batch_alter_table('wishlist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_updated', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wishlist', schema=None) as batch_op:
        batch_op.drop_column('last_updated')

    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.drop_column('last_updated')

    # ### end Alembic commands ###
