"""Perbaiki Struktur Table

Revision ID: 92f9a535e916
Revises: 090d67efeb65
Create Date: 2024-10-03 04:02:53.546582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92f9a535e916'
down_revision = '090d67efeb65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discount', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_added', sa.DateTime(), nullable=True))

    with op.batch_alter_table('gallery', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_added', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_updated', sa.DateTime(), nullable=True))

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_added', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_updated', sa.DateTime(), nullable=True))

    with op.batch_alter_table('shoe_category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_added', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_updated', sa.DateTime(), nullable=True))

    with op.batch_alter_table('shoe_detail', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_added', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_updated', sa.DateTime(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_added', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_updated', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_updated')
        batch_op.drop_column('date_added')

    with op.batch_alter_table('shoe_detail', schema=None) as batch_op:
        batch_op.drop_column('last_updated')
        batch_op.drop_column('date_added')

    with op.batch_alter_table('shoe_category', schema=None) as batch_op:
        batch_op.drop_column('last_updated')
        batch_op.drop_column('date_added')

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('last_updated')
        batch_op.drop_column('date_added')

    with op.batch_alter_table('gallery', schema=None) as batch_op:
        batch_op.drop_column('last_updated')
        batch_op.drop_column('date_added')

    with op.batch_alter_table('discount', schema=None) as batch_op:
        batch_op.drop_column('date_added')

    # ### end Alembic commands ###
