"""Perbaiki Struktur Table"

Revision ID: f99e85b98ef3
Revises: 3ed8fe3f1738
Create Date: 2024-10-03 17:14:06.557088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f99e85b98ef3'
down_revision = '3ed8fe3f1738'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('date_added')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_added', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
